### ISSUE TITLE
COMPARE metric in testset.tsv does not correspond to score in raw_annotations.tsv for some word

### ISSUE THREAD

**Issue by nvanva** [juliarodina/RuSemShift#3]
When calculating COMPARE metric from raw_annotations.tsv by averaging over sentence pair scores of type COMPARE for each word, for several words the results is not equal to the COMPARE metric in testset.tsv.
There 6 such words in rusemshift_1 and 19 in rusemshift_2.

![image](https://user-images.githubusercontent.com/9987540/107889306-b0294d00-6f22-11eb-9ed7-b071e20b406b.png)

**Comment by juliarodina** [comment]
We excluded pairs of sentences with 0-judgements (Cannot decide), 
`raw_annots = raw_annots[(raw_annots.annotator1 != 0) & (raw_annots.annotator2 != 0) & (raw_annots.annotator3 != 0)
                    & (raw_annots.annotator4 != 0) & (raw_annots.annotator5 != 0)]`
